//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecificSolutions.Endowment.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecificSolutions.Endowment.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف مطلوب.
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة مطلوب.
        /// </summary>
        public static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string CityNameMaxLength {
            get {
                return ResourceManager.GetString("CityNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string CityNameInvalidCharacters {
            get {
                return ResourceManager.GetString("CityNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدولة مطلوب.
        /// </summary>
        public static string CityCountryRequired {
            get {
                return ResourceManager.GetString("CityCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدولة يجب أن لا يتجاوز 100 حرف.
        /// </summary>
        public static string CityCountryMaxLength {
            get {
                return ResourceManager.GetString("CityCountryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدولة يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string CityCountryInvalidCharacters {
            get {
                return ResourceManager.GetString("CityCountryInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة مطلوب.
        /// </summary>
        public static string CityIdRequired {
            get {
                return ResourceManager.GetString("CityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مطلوبة.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحساب مطلوب.
        /// </summary>
        public static string AccountNameRequired {
            get {
                return ResourceManager.GetString("AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحساب يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string AccountNameMaxLength {
            get {
                return ResourceManager.GetString("AccountNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحساب يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string AccountNameInvalidCharacters {
            get {
                return ResourceManager.GetString("AccountNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم مطلوب.
        /// </summary>
        public static string MotherNameRequired {
            get {
                return ResourceManager.GetString("MotherNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string MotherNameMaxLength {
            get {
                return ResourceManager.GetString("MotherNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string MotherNameInvalidCharacters {
            get {
                return ResourceManager.GetString("MotherNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد مطلوب.
        /// </summary>
        public static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد لا يمكن أن يكون في المستقبل.
        /// </summary>
        public static string BirthDateNotInFuture {
            get {
                return ResourceManager.GetString("BirthDateNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد غير صحيح.
        /// </summary>
        public static string BirthDateInvalid {
            get {
                return ResourceManager.GetString("BirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس غير صحيح.
        /// </summary>
        public static string GenderInvalid {
            get {
                return ResourceManager.GetString("GenderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود مطلوب.
        /// </summary>
        public static string BarcodeRequired {
            get {
                return ResourceManager.GetString("BarcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string BarcodeMaxLength {
            get {
                return ResourceManager.GetString("BarcodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة غير صحيحة.
        /// </summary>
        public static string StatusInvalid {
            get {
                return ResourceManager.GetString("StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم ملف الخزانة يجب أن يكون أكبر من صفر.
        /// </summary>
        public static string LockerFileNumberGreaterThanZero {
            get {
                return ResourceManager.GetString("LockerFileNumberGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية غير صحيحة.
        /// </summary>
        public static string SocialStatusInvalid {
            get {
                return ResourceManager.GetString("SocialStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب مطلوب.
        /// </summary>
        public static string AccountNumberRequired {
            get {
                return ResourceManager.GetString("AccountNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string AccountNumberMaxLength {
            get {
                return ResourceManager.GetString("AccountNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب غير صحيح.
        /// </summary>
        public static string AccountTypeInvalid {
            get {
                return ResourceManager.GetString("AccountTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني يجب أن يكون أكبر من صفر.
        /// </summary>
        public static string NIDGreaterThanZero {
            get {
                return ResourceManager.GetString("NIDGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد لا يمكن أن يكون سالب.
        /// </summary>
        public static string BalanceNotNegative {
            get {
                return ResourceManager.GetString("BalanceNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظة يجب أن لا تتجاوز 1000 حرف.
        /// </summary>
        public static string NoteMaxLength {
            get {
                return ResourceManager.GetString("NoteMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكتاب لا يمكن أن يكون سالب.
        /// </summary>
        public static string BookNumberNotNegative {
            get {
                return ResourceManager.GetString("BookNumberNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الورقة لا يمكن أن يكون سالب.
        /// </summary>
        public static string PaperNumberNotNegative {
            get {
                return ResourceManager.GetString("PaperNumberNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التسجيل لا يمكن أن يكون سالب.
        /// </summary>
        public static string RegistrationNumberNotNegative {
            get {
                return ResourceManager.GetString("RegistrationNumberNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان يجب أن لا يتجاوز 500 حرف.
        /// </summary>
        public static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة يجب أن لا تتجاوز 100 حرف.
        /// </summary>
        public static string CityMaxLength {
            get {
                return ResourceManager.GetString("CityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد يجب أن لا يتجاوز 100 حرف.
        /// </summary>
        public static string CountryMaxLength {
            get {
                return ResourceManager.GetString("CountryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاتصال غير صحيح.
        /// </summary>
        public static string ContactNumberInvalid {
            get {
                return ResourceManager.GetString("ContactNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الطوابق لا يمكن أن يكون سالب.
        /// </summary>
        public static string FloorsNotNegative {
            get {
                return ResourceManager.GetString("FloorsNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الطوابق لا يمكن أن يتجاوز 100.
        /// </summary>
        public static string FloorsMaxValue {
            get {
                return ResourceManager.GetString("FloorsMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القرار مطلوب.
        /// </summary>
        public static string DecisionTitleRequired {
            get {
                return ResourceManager.GetString("DecisionTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القرار يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string DecisionTitleMaxLength {
            get {
                return ResourceManager.GetString("DecisionTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القرار يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string DecisionTitleInvalidCharacters {
            get {
                return ResourceManager.GetString("DecisionTitleInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف القرار مطلوب.
        /// </summary>
        public static string DecisionDescriptionRequired {
            get {
                return ResourceManager.GetString("DecisionDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف القرار يجب أن لا يتجاوز 1000 حرف.
        /// </summary>
        public static string DecisionDescriptionMaxLength {
            get {
                return ResourceManager.GetString("DecisionDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف القرار يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string DecisionDescriptionInvalidCharacters {
            get {
                return ResourceManager.GetString("DecisionDescriptionInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع مطلوب.
        /// </summary>
        public static string ReferenceNumberRequired {
            get {
                return ResourceManager.GetString("ReferenceNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string ReferenceNumberMaxLength {
            get {
                return ResourceManager.GetString("ReferenceNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string ReferenceNumberInvalidCharacters {
            get {
                return ResourceManager.GetString("ReferenceNumberInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء مطلوب.
        /// </summary>
        public static string CreatedDateRequired {
            get {
                return ResourceManager.GetString("CreatedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة مطلوب.
        /// </summary>
        public static string RegionNameRequired {
            get {
                return ResourceManager.GetString("RegionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string RegionNameMaxLength {
            get {
                return ResourceManager.GetString("RegionNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string RegionNameInvalidCharacters {
            get {
                return ResourceManager.GetString("RegionNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المكتب مطلوب.
        /// </summary>
        public static string OfficeNameRequired {
            get {
                return ResourceManager.GetString("OfficeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المكتب يجب أن لا يتجاوز 200 حرف.
        /// </summary>
        public static string OfficeNameMaxLength {
            get {
                return ResourceManager.GetString("OfficeNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المكتب يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string OfficeNameInvalidCharacters {
            get {
                return ResourceManager.GetString("OfficeNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صحيح.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المكتب مطلوب.
        /// </summary>
        public static string OfficeLocationRequired {
            get {
                return ResourceManager.GetString("OfficeLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المكتب يجب أن لا يتجاوز 500 حرف.
        /// </summary>
        public static string OfficeLocationMaxLength {
            get {
                return ResourceManager.GetString("OfficeLocationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المكتب يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string OfficeLocationInvalidCharacters {
            get {
                return ResourceManager.GetString("OfficeLocationInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الطلب مطلوب.
        /// </summary>
        public static string RequestTitleRequired {
            get {
                return ResourceManager.GetString("RequestTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الطلب يجب أن يكون بين 1 و 100 حرف.
        /// </summary>
        public static string RequestTitleLength {
            get {
                return ResourceManager.GetString("RequestTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الطلب يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string RequestTitleInvalidCharacters {
            get {
                return ResourceManager.GetString("RequestTitleInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الطلب مطلوب.
        /// </summary>
        public static string RequestDescriptionRequired {
            get {
                return ResourceManager.GetString("RequestDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الطلب يجب أن يكون بين 1 و 500 حرف.
        /// </summary>
        public static string RequestDescriptionLength {
            get {
                return ResourceManager.GetString("RequestDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الطلب يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string RequestDescriptionInvalidCharacters {
            get {
                return ResourceManager.GetString("RequestDescriptionInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إنشاء الطلب مطلوب.
        /// </summary>
        public static string RequestCreatedDateRequired {
            get {
                return ResourceManager.GetString("RequestCreatedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إنشاء الطلب لا يمكن أن يكون في المستقبل.
        /// </summary>
        public static string RequestCreatedDateNotInFuture {
            get {
                return ResourceManager.GetString("RequestCreatedDateNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول مطلوب.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string FirstNameInvalidCharacters {
            get {
                return ResourceManager.GetString("FirstNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير مطلوب.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string LastNameInvalidCharacters {
            get {
                return ResourceManager.GetString("LastNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني يجب أن لا يتجاوز 100 حرف.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم مطلوب.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string UserNameInvalidCharacters {
            get {
                return ResourceManager.GetString("UserNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن تكون 6 أحرف على الأقل.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن لا تتجاوز 100 حرف.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور مطلوب.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور وتأكيدها غير متطابقين.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان مطلوب.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان يحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string AddressInvalidCharacters {
            get {
                return ResourceManager.GetString("AddressInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة مطلوبة.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة تحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string CityInvalidCharacters {
            get {
                return ResourceManager.GetString("CityInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة مطلوبة.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة تحتوي على أحرف غير مسموحة.
        /// </summary>
        public static string CountryInvalidCharacters {
            get {
                return ResourceManager.GetString("CountryInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتب مطلوب.
        /// </summary>
        public static string OfficeRequired {
            get {
                return ResourceManager.GetString("OfficeRequired", resourceCulture);
            }
        }
    }
} 